install.packages(c("ggplot2", "dplyr", "magrittr", "readr", "shiny", "googleLanguageR"))
install.packages('tidyverse')
install.packages('rvest')
install.packages('splitstackshape')
install.packages("GGally")
install.packages("devtools")
devtools::install_github("briatte/ggnet")
install.packages("RecordLinkage")
